Repository youzan/zent, pull requests merged in 2018-04, with the labels that each got.

#785 [bug fix] Pop: Fix incorrect position in popover
  packages/zent/src/popover/Content.js
  packages/zent/src/popover/placement/isEqual.js
  packages/zent/src/portal/Portal.js
  packages/zent/src/portal/README_en-US.md
  packages/zent/src/portal/README_zh-CN.md
  packages/zent/src/portal/demos/basic.md
  packages/zent/src/portal/util.js
Labels: bug

#791 [bug fix] Form: Fix asyncValidate return value in Form
  packages/zent/src/block-header/BlockHeader.js
  packages/zent/src/design/README_zh-CN.md
  packages/zent/src/form/createForm.js
  scripts/check-git-hooks.sh
Labels: bug

#790 [new feature] previewImage: 支持预览图片的缩放
  packages/zent/assets/preview-image.pcss
  packages/zent/src/preview-image/Image.js
  packages/zent/src/preview-image/README_en-US.md
  packages/zent/src/preview-image/README_zh-CN.md
  packages/zent/src/preview-image/demos/basic.md
Labels: help wanted

#794 [new feature] ErrorBoundary: Add ErrorBoundary component
  packages/zent/__tests__/error-boundary.js
  packages/zent/assets/error-boundary.pcss
  packages/zent/assets/index.pcss
  packages/zent/jest.config.json
  packages/zent/src/error-boundary/ErrorBoundary.js
  packages/zent/src/error-boundary/Fallback.js
  packages/zent/src/error-boundary/README_en-US.md
  packages/zent/src/error-boundary/README_zh-CN.md
  packages/zent/src/error-boundary/demos/basic.md
  packages/zent/src/error-boundary/demos/custom.md
  packages/zent/src/error-boundary/demos/hoc.md
  packages/zent/src/error-boundary/demos/on-error.md
  packages/zent/src/error-boundary/index.js
  packages/zent/src/error-boundary/withErrorBoundary.js
  packages/zent/src/index.js
  packages/zent/typings/index.d.ts
  packages/zent/typings/libs/ErrorBoundary.d.ts
Labels: enhancement

#798 [bug fix] Loading: Fix height not applied
  packages/zent/src/loading/Loading.js
  packages/zent/src/loading/README_en-US.md
  packages/zent/src/loading/README_zh-CN.md
  packages/zent/src/loading/demos/wrapper-mode.md
Labels: bug

#799 [doc] 更新中英文文档截图
  packages/zent/README_en-US.md
  packages/zent/README_zh-CN.md
  packages/zent/src/form/demos/buildin-field.md
Labels: doc

#803 [bug fix] Form: fix corner cases in scrollToFirstError
  package.json
  packages/zent/__tests__/date-range-quick-picker.js
  packages/zent/__tests__/form/Form.js
  packages/zent/__tests__/form/GetControlGroup-Component_Fields.js
  packages/zent/docs/CONTRIBUTING_en-US.md
  packages/zent/docs/CONTRIBUTING_zh-CN.md
  packages/zent/src/datetimepicker/DateRangePicker.js
  packages/zent/src/form/README_en-US.md
  packages/zent/src/form/README_zh-CN.md
  packages/zent/src/form/form-components/ColorPickerField.js
  packages/zent/src/form/form-components/DateRangePickerField.js
  packages/zent/src/form/form-components/DateRangeQuickPickerField.js
  packages/zent/src/form/form-components/FormComponentField.js
  packages/zent/src/form/form-components/NumberInputField.js
  packages/zent/src/form/form-components/SwitchField.js
  packages/zent/src/form/index.js
  packages/zent/src/form/utils.js
  scripts/test-component.sh
  scripts/test.sh
Labels: bug
