Repository youzan/zent, pull requests merged in 2018-05, with the labels that each got.

#816 [bug fix] Grid: 增加 Grid.d.ts
  packages/zent/typings/index.d.ts
  packages/zent/typings/libs/Grid.d.ts
Labels: enhancement

#817 [new feature] Mention
  packages/zent/assets/_popup-menu.pcss
  packages/zent/assets/animation/_zoom.pcss
  packages/zent/assets/animation/index.pcss
  packages/zent/assets/auto-complete.pcss
  packages/zent/assets/base.pcss
  packages/zent/assets/base/_popup.pcss
  packages/zent/assets/dialog.pcss
  packages/zent/assets/index.pcss
  packages/zent/assets/input.pcss
  packages/zent/assets/mention.pcss
  packages/zent/assets/mixins/_popup-menu-item.pcss
  packages/zent/assets/mixins/_popup.pcss
  packages/zent/assets/mixins/index.pcss
  packages/zent/assets/select-menu.pcss
  packages/zent/assets/select.pcss
  packages/zent/jest.config.json
  packages/zent/scripts/generate-module-config.js
  packages/zent/src/auto-complete/AutoComplete.js
  packages/zent/src/auto-complete/demos/basic.md
  packages/zent/src/dialog/Dialog.js
  packages/zent/src/dialog/DialogEl.js
  packages/zent/src/i18n/en-US.js
  packages/zent/src/i18n/zh-CN.js
  packages/zent/src/index.js
  packages/zent/src/mention/Mention.js
  packages/zent/src/mention/README_en-US.md
  packages/zent/src/mention/README_zh-CN.md
  packages/zent/src/mention/SelectionChangeEventHub.js
  packages/zent/src/mention/demos/basic.md
  packages/zent/src/mention/demos/multi-line.md
  packages/zent/src/mention/demos/position.md
  packages/zent/src/mention/index.js
  packages/zent/src/popover/trigger/Trigger.js
  packages/zent/src/select-menu/MenuList.js
  packages/zent/src/select-menu/SelectMenu.js
  packages/zent/src/select-menu/index.js
  packages/zent/src/utils/component/animatedClosable.js
  packages/zent/src/utils/component/index.js
  packages/zent/src/utils/dom/getCaretCoordinates.js
  packages/zent/src/utils/isFirefox.js
Labels: enhancement

#819 [new feature] Mention: Add typescript definition for Mention
  packages/zent/src/mention/Mention.js
  packages/zent/typings/index.d.ts
  packages/zent/typings/libs/Mention.d.ts
Labels: enhancement

#818 [bug fix] Pagination: Add onPageSizeChange callback
  packages/zent/__tests__/pagination.js
  packages/zent/src/pagination/README_en-US.md
  packages/zent/src/pagination/README_zh-CN.md
  packages/zent/src/pagination/demos/dynamic-page-size.md
  packages/zent/src/pagination/index.js
  packages/zent/typings/libs/Pagination.d.ts
Labels: bug

#826 [new feature] Icon: Add new icons
  packages/zent/package.json
  packages/zent/src/icon/demos/all.md
  packages/zent/yarn.lock
Labels: enhancement

#823 [bug fix]DateRangePickerField and DateRangeQuickPickerField: change date's prop 'format' to 'dateFormat'
  packages/zent/src/form/README_en-US.md
  packages/zent/src/form/README_zh-CN.md
  packages/zent/src/form/demos/buildin-field.md
  packages/zent/src/form/form-components/DateRangePickerField.js
  packages/zent/src/form/form-components/DateRangeQuickPickerField.js
Labels: bug

#830 [doc] Tabs: 更新 tabs id 类型说明
  packages/zent/src/tabs/README_en-US.md
  packages/zent/src/tabs/README_zh-CN.md
Labels: doc

#832 [bug fix] Inout: Fix Input addon style
  packages/zent/assets/input.pcss
  packages/zent/src/input/demos/event-handler.md
Labels: bug

#831 [bug fix] support multi ops called synchronously for FieldArray
  packages/zent/__tests__/form/CreateForm-FieldArray.js
  packages/zent/src/form/FieldArray.js
  packages/zent/src/form/README_en-US.md
  packages/zent/src/form/README_zh-CN.md
  packages/zent/src/form/demos/field-array.md
Labels: bug

#833 [bug fix] Loading: fix loading cannot be close because ReactDOM.render return null
  packages/zent/src/loading/LoadingInstance.js
Labels: bug

#839 [bug fix]Mention: Fix incorrect position when input has suffix or prefix
  .stylelintrc
  packages/zent/__tests__/popover.js
  packages/zent/src/mention/Mention.js
  packages/zent/src/mention/constants.js
  packages/zent/src/mention/demos/with-input-prefix.md
  packages/zent/src/mention/findMentionAtCaretPosition.js
  packages/zent/src/mention/position.js
  packages/zent/src/mention/utils.js
  packages/zent/src/popover/Popover.js
  packages/zent/src/popover/README_en-US.md
  packages/zent/src/popover/README_zh-CN.md
  packages/zent/src/popover/trigger/Trigger.js
  packages/zent/typings/libs/Popover.d.ts
Labels: bug

#811 [new feature] Timeline组件
  packages/zent/__tests__/timeline.js
  packages/zent/assets/index.pcss
  packages/zent/assets/timeline.pcss
  packages/zent/jest.config.json
  packages/zent/src/index.js
  packages/zent/src/timeline/Dot.js
  packages/zent/src/timeline/Item.js
  packages/zent/src/timeline/README_en-US.md
  packages/zent/src/timeline/README_zh-CN.md
  packages/zent/src/timeline/Timeline.js
  packages/zent/src/timeline/demos/array.md
  packages/zent/src/timeline/demos/basic.md
  packages/zent/src/timeline/demos/dynamic.md
  packages/zent/src/timeline/index.js
  packages/zent/src/timeline/validateProps.js
  packages/zent/typings/index.d.ts
  packages/zent/typings/libs/Timeline.d.ts
Labels: enhancement

#841 [breaking change] Loading: Remove deprecated methods on/off/newInstance
  packages/zent/__tests__/loading.js
  packages/zent/src/loading/LoadingInstance.js
Labels: backwards-incompatible

#845 [bug fix] Dialog: 增加isBrowser判断
  packages/zent/src/dialog/Dialog.js
Labels: bug

#847 [bug fix] Form: Support setting value on FieldArray
  packages/zent/__tests__/form/CreateForm-FieldArray.js
  packages/zent/__tests__/form/Utils.js
  packages/zent/__tests__/preview-image.js
  packages/zent/src/form/Field.js
  packages/zent/src/form/FieldArray.js
  packages/zent/src/form/README_en-US.md
  packages/zent/src/form/README_zh-CN.md
  packages/zent/src/form/constants.js
  packages/zent/src/form/createForm.js
  packages/zent/src/form/demos/basic.md
  packages/zent/src/form/demos/field-array.md
  packages/zent/src/form/demos/form-section.md
  packages/zent/src/form/utils.js
  packages/zent/src/preview-image/Image.js
  packages/zent/src/preview-image/previewImage.js
Labels: bug
