Repository youzan/zent, pull requests merged in 2018-06, with the labels that each got.

#855 [bugfix] 移除Grid中的cloneDeep
  packages/zent/src/grid/Grid.js
Labels: bug

#853 [bug fix] Timeline: 组件修改弹层定位
  packages/zent/src/timeline/Item.js
  packages/zent/src/timeline/Timeline.js
Labels: bug

#858 [new feature] Add more form date field
  packages/zent/__tests__/form/GetControlGroup-Component_Fields.js
  packages/zent/src/datetimepicker/DatePicker.js
  packages/zent/src/datetimepicker/DateRangePicker.js
  packages/zent/src/datetimepicker/MonthPicker.js
  packages/zent/src/datetimepicker/QuarterPicker.js
  packages/zent/src/datetimepicker/README_en-US.md
  packages/zent/src/datetimepicker/README_zh-CN.md
  packages/zent/src/datetimepicker/TimePicker.js
  packages/zent/src/datetimepicker/TimeRangePicker.js
  packages/zent/src/datetimepicker/WeekPicker.js
  packages/zent/src/datetimepicker/YearPicker.js
  packages/zent/src/form/README_en-US.md
  packages/zent/src/form/README_zh-CN.md
  packages/zent/src/form/form-components/DatePickerField.js
  packages/zent/src/form/form-components/FormComponentField.js
  packages/zent/src/form/form-components/MonthPickerField.js
  packages/zent/src/form/form-components/QuarterPickerField.js
  packages/zent/src/form/form-components/TimePickerField.js
  packages/zent/src/form/form-components/TimeRangePickerField.js
  packages/zent/src/form/form-components/WeekPickerField.js
  packages/zent/src/form/form-components/YearPickerField.js
  packages/zent/src/form/index.js
Labels: enhancement

#859 [new fature] Form: Allow non stardard value in Field onChange and onBlur
  packages/zent/__tests__/form/CreateForm-Field.js
  packages/zent/__tests__/form/Utils.js
  packages/zent/src/form/Field.js
  packages/zent/src/form/utils.js
Labels: enhancement

#860 [bug fix] Collapse: Fix Collpase activeKey prop type declaration
  packages/zent/src/collapse/Collapse.js
  packages/zent/src/collapse/README_en-US.md
  packages/zent/src/collapse/README_zh-CN.md
  packages/zent/typings/libs/Collapse.d.ts
Labels: bug

#861 [bug fix] DatePicker: Remove onBlur and onFocus callback from date pickers
  packages/zent/assets/datetimepicker.pcss
  packages/zent/src/datetimepicker/DatePicker.js
  packages/zent/src/datetimepicker/MonthPicker.js
  packages/zent/src/datetimepicker/QuarterPicker.js
  packages/zent/src/datetimepicker/TimePicker.js
  packages/zent/src/datetimepicker/WeekPicker.js
  packages/zent/src/datetimepicker/YearPicker.js
  packages/zent/src/datetimepicker/constants/index.js
Labels: bug

#863 Move docs to github pages
  site/README.md
  site/assets/ZanUIlogo256x256.png
  site/assets/zanui-logo.png
  site/package.json
  site/scripts/deploy.sh
  site/src/404.html
  site/src/components/page-footer/index.js
  site/src/constants.js
  site/src/index.html
  site/webpack/webpack.config.js
  site/webpack/webpack.prd.config.js
  site/yarn.lock
Labels: doc

#869 [enhancement] ErrorBoundary: Update ErrorBoundary HOC
  packages/zent/__tests__/error-boundary.js
  packages/zent/src/error-boundary/README_en-US.md
  packages/zent/src/error-boundary/README_zh-CN.md
  packages/zent/src/error-boundary/catchError.js
  packages/zent/src/error-boundary/demos/hoc.md
  packages/zent/src/error-boundary/index.js
Labels: enhancement

#873 [bug fix] Select: 修复因为类名变更导致的默认样式丢失问题
  packages/zent/assets/select.pcss
Labels: bug

#874 [bug fix] Card: remove unnecessary style
  packages/zent/CHANGELOG.md
  packages/zent/assets/card.pcss
Labels: bug

#875 [new feature] Icon: Add new icons
  .circleci/config.yml
  .travis.yml
  packages/zent/package.json
  packages/zent/src/icon/demos/all.md
  packages/zent/yarn.lock
Labels: bug

#879 [bug fix] Fix ts definitions
  packages/zent/typings/index.d.ts
  packages/zent/typings/libs/SplitButton.d.ts
  packages/zent/typings/libs/Timeline.d.ts
Labels: bug
