Repository youzan/zent, pull requests merged in 2021-03, with the labels that each got.

#1675 [Upload] bugfix: 修复 onUpload 返回值不会覆盖到 item 上的问题
  packages/zent/src/upload/README_en-US.md
  packages/zent/src/upload/README_zh-CN.md
  packages/zent/src/upload/SingleUpload.tsx
  packages/zent/src/upload/components/AbstractMultiUpload.tsx
  packages/zent/src/upload/components/AbstractUpload.tsx
  packages/zent/src/upload/components/normal/List.tsx
  packages/zent/src/upload/demos/pagination.md
  packages/zent/src/upload/types.ts
  packages/zent/src/upload/utils/default-image-props.ts
Labels: bug, doc

#1674 update logo, update zan design website url
  README-zh_CN.md
  README.md
  packages/zent/RELEASE_en-US.md
  packages/zent/RELEASE_zh-CN.md
  site/src/components/page-header/index.js
Labels: doc

#1676 bugfix: [Upload] 修复 onUpload 返回的 Promise resolve 属性不覆盖的问题
  packages/zent/src/upload/components/AbstractUpload.tsx
Labels: bug

#1677 send wechat work notification when a new release is published
  .github/workflows/release.yml
Labels: doc

#1682 update form doc
  packages/zent/src/form/README_zh-CN.md
Labels: doc

#1683 update validate options doc
  packages/zent/src/form/README_zh-CN.md
  packages/zent/src/form/demos/5.async-validate.md
Labels: doc
